name: xylophone_version_one
description: "Xylophone Sound App. This is First Try Of creating It and It is Simple project."

publish_to: "none"

homepage: https://github.com/KASRA10/xylophone_version_one.git
issue_tracker: https://github.com/KASRA10/xylophone_version_one.git
documentation: https://github.com/KASRA10/xylophone_version_one.git
repository: https://github.com/KASRA10/xylophone_version_one.git

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #         style: italic
